server:
  port: 8899
  servlet:
    context-path: /mybatis

spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/aum?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: allcom
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: false

logging:
  file: /applog/logs/spring-mybatis.log
  level:
    com.allcom: info

